### ISSUE TITLE
Unrecoverable error: rangecheck in .putdeviceprops

### ISSUE THREAD

**Issue by MaxMatti** [tavinus/pdfScale#1]
I am having the following problem:

$ ./pdfScale.sh -s 0.9 infile.pdf outfile.pdf
Unrecoverable error: rangecheck in .putdeviceprops
$ ./pdfScale.sh -v -s 0.9 infile.pdf outfile.pdf                                                                             
pdfScale.sh v1.0.11 - Verbose execution
Checking dependencies
  Scale factor: 0.9
    Input file: infile.pdf
   Output file: outfile.pdf
         Width: 0 postscript-points
        Height: 0 postscript-points
 Translation X: 0
 Translation Y: 0
Unrecoverable error: rangecheck in .putdeviceprops

I have no clue what's causing this or why. The input is a DIN-A4 PDF-File with 105 pages produced by pdfnup.

**Comment by tavinus** [comment]
humm.. can you annex that PDF so I can test it?
Also, what system are you running this?

```Width: 0 postscript-points
Height: 0 postscript-points
Translation X: 0
Translation Y: 0```
These should not be Zero, something is going wrong there...

**Comment by MaxMatti** [comment]
I have an older Linux Mint (17.1) with a kernel 3.13 on an x86_64bit pc.
The cat/grep command returns no output.
I can't publish the original PDF here but I will try to find something that I can publish where I have the problem.

**Comment by MaxMatti** [comment]
Ok, both files have been created with pdfnup, for the attached file I just removed all pages except for two before running pdfnup.
Output this time:

	$ pdftk file.pdf cat 3-4 output /tmp/input.pdf
	$ pdfnup /tmp/input.pdf 
	          ----
	  pdfjam: This is pdfjam version 2.08.
	  pdfjam: Reading any site-wide or user-specific defaults...
	          (none found)
	  pdfjam: Effective call for this run of pdfjam:
	          /usr/bin/pdfjam --suffix nup --nup '2x1' --landscape -- /tmp/input.pdf - 
	  pdfjam: Calling pdflatex...
	  pdfjam: Finished.  Output was to '/home/user/input-nup.pdf'.
	$ ./pdfScale.sh -v -s 0.9 input-nup.pdf out.pdf 
	pdfScale.sh v1.0.11 - Verbose execution
	Checking dependencies
	  Scale factor: 0.9
	    Input file: input-nup.pdf
	   Output file: out.pdf
	         Width: 0 postscript-points
	        Height: 0 postscript-points
	 Translation X: 0
	 Translation Y: 0
	Unrecoverable error: rangecheck in .putdeviceprops

[input-nup.pdf](https://github.com/tavinus/pdfScale/files/786076/input-nup.pdf)
[out.pdf](https://github.com/tavinus/pdfScale/files/786075/out.pdf)
[input.pdf](https://github.com/tavinus/pdfScale/files/786077/input.pdf)

**Comment by tavinus** [comment]
Ok, thanks for the info and for the files.

If the cat + grep command does not work, nothing else will work, since we won't have a valid paper size to base the resizing on.

The file input.pdf works fine here (it finds de MediaBox definition, and also resizes):
```
$ cat input.pdf | grep -a '/MediaBox'
/MediaBox [0 0 595.32 841.92]
/MediaBox [0 0 595.32 841.92]
```
```
$ pdfScale-master/pdfScale.sh -v -s 0.9 input.pdf 
pdfScale.sh v1.0.11 - Verbose execution
Checking dependencies
  Scale factor: 0.9
    Input file: input.pdf
   Output file: input.SCALED.pdf
         Width: 595 postscript-points
        Height: 842 postscript-points
 Translation X: 33.055225
 Translation Y: 46.777310
````
File: [input.SCALED.pdf](https://github.com/tavinus/pdfScale/files/788880/input.SCALED.pdf)
 
The file input-nup.pdf though has no MediaBox definition. So this one fails when greping for the page size. I have found a `/BBox [0 0 595.32 841.92]` on that file. That is an A4 size in postscript points. Honestly, I am not sure why you don't have a Mediabox on your pdf, but I am just now creating a version that will try to use `/BBox` if `/Mediabox` is not available and then abort execution if none of them is available.

I will post it soon.
Cheers!
Gus

**Comment by tavinus** [comment]
Please try to use the new version on your problematic files and let me know.
[pdfScale v1.1.3](https://github.com/tavinus/pdfScale/releases/tag/1.1.3)

**Comment by MaxMatti** [comment]
Okok calm down I just got up and read this. I will try that now.

**Comment by tavinus** [comment]
Just get the latest master or tag and try ;)  
I went a long way talking too much.  
I try not to do that, but well... I fail... LOL

**Comment by MaxMatti** [comment]
Looks good to me at first glance.
However in case you want it to be very exact: Try scaling the output of pdfnup with `-s 0.5`. It's a little bit off center.
It seems to me as if it's always a little bit off center but too little to notice unless using a way to small parameter.
Doesn't bother me, just wanted to mention that.

I was just referring to the final edit where you said "Let me know so we can close this please." because in my head it sounded like you have waited a few days already.

**Comment by MaxMatti** [comment]
Oh and with the `-i` parameter it works just fine. No offset there.

**Comment by MaxMatti** [comment]
Now I want to know: Should I always use `-i` or just when it's offcenter without `-i`? And if I should always use it why make it a parameter and not include it or put the parameter the other way around (so it's enabled by default)?

**Comment by tavinus** [comment]
Humm... the really weird thing is that the sizes rendered with and without imagemagick are the same. I mean, try posting the verbose output both with and without the -i parameter here.   
I prefer not to use `-i` by default because it creates a new dependency.

**Comment by tavinus** [comment]
Ok, not quite... the values are inverted in your file when not using `identify`:
```
$ ./pdfScale.sh -v -s 0.5 ../input-nup.pdf
pdfScale.sh v1.2.10 - Verbose execution
Checking for ghostscript and bcmath
  Scale factor: 0.5
    Input file: ../input-nup.pdf
   Output file: ../input-nup.SCALED.pdf
         Width: 595 postscript-points
        Height: 842 postscript-points
 Translation X: 297.500000
 Translation Y: 421.000000
```
```
$ ./pdfScale.sh -i -v -s 0.5 ../input-nup.pdf
pdfScale.sh v1.2.10 - Verbose execution
Checking for ghostscript and bcmath
Checking for imagemagick's identify
  Scale factor: 0.5
    Input file: ../input-nup.pdf
   Output file: ../input-nup.SCALED.pdf
         Width: 842 postscript-points
        Height: 595 postscript-points
 Translation X: 421.000000
 Translation Y: 297.500000
```
I wonder if I can just check which one is bigger and assign it to the width.

**Comment by tavinus** [comment]
The BBox is really set like that, not sure now.
```
/BBox [0 0 595.32 841.92]
```
I couldn't find a way to determine if it is landscape either.
Can you please create a n-up file that is not landscape so I can check its BBox declaration?

**Comment by tavinus** [comment]
Aright dude...
v1.3.1 is out. You made me think that I should be able to get the page size using ghostscript. I then found a solution but it involved an external PostScript file. I then embedded that file into my script and it is now working fine.   
 
People can still use the older cat + grep method with the `-c` parameter.

This version should not require the `-i` or `-c` parameters to work correctly though. If anything, you will still have problems when using the `-c` option. I myself have use cases for `-c`, so I kept it.

**Comment by tavinus** [comment]
Please let me know if the new version works well for you.
Cheers!

**Comment by MaxMatti** [comment]
Ok, but I don't have the time right now (big test tomorrow), so I will try that in >36h. Sorry for the delay.

**Comment by tavinus** [comment]
No worries

**Comment by tavinus** [comment]
Please do not use version 1.3.x that are before 1.3.5.
The input file name was hard-coded there.
Fixed now.
Cheers!

**Comment by tavinus** [comment]
ok... I was studying Postscript and trying to make something myself but hat is not going to well. Also, I am not sure about the license of the embedded script so I removed it.   
 
What I did now, is to create an adaptive method for page sizing. It will try cat+grep, mdls, pdfinfo, identify, then fail. This way should be fine on most systems and people can always force a method with the `-m` parameter.   
 
Your n-up file for example, failed for me on cat+grep but then went fine on mdls and pdfinfo (automatically). Basically, if there is no `/MediaBox` declaration on the PDF, the cat+grep method will fail, on which case you will need to have one of the other external options for the script to run. Having a single one of them available is enough.
 
[You can get the new version here v1.4.5.](https://github.com/tavinus/pdfScale/releases/tag/1.4.5)
