### ISSUE TITLE
./Makefile doesn't work

### ISSUE THREAD

**Issue by Cellomaster87** [tavinus/pdfScale#12]
Running ./Makefile gives me the following output and then, of course, nothing works.

Dragging / dropping the pdfscale.sh manually into the usr/local/bin directory makes it work but I guess this is not intended. 

<img width="569" alt="screen shot 2018-11-04 at 12 31 25" src="https://user-images.githubusercontent.com/31044692/47964472-f94b8080-e03a-11e8-9ad8-6e93d927659c.png">

**Comment by tavinus** [comment]
Hi,  
  
That is not really how you run a Makefile (it is not an executable file).  
You should just call `make <target>`.  
The `make` utility reads the file `Makefile` for its targets.  
  
As mentioned in the [Readme.md](https://github.com/tavinus/pdfScale/blob/master/README.md#install-with-make), just call:
```
sudo make install
```
You will need to have `make` installed  
(eg. `sudo apt-get install make`)
  
Or you can do without make using the `-i`, or `--install` option, as in:
```
./pdfScale.sh --install
```
Cheers!  
Gus

**Comment by Cellomaster87** [comment]
Thank you very much!

Michele Galvagno

michicello@gmail.com
Tel: +39 327 584 64 64

**Comment by tavinus** [comment]
No worries mate!  
Cheers!  
Gus
