### ISSUE TITLE
can i add border to the pages after fitting them

### ISSUE THREAD

**Issue by sant527** [tavinus/pdfScale#13]
I want to resize my pdf to A4 but also i want to check the pages how much extent they are resized. So is it possible to add a border to the original pages in the resized document

**Comment by tavinus** [comment]
Hi! I am not sure I understand your question.  
Maybe just RESIZE + SCALE is what you want?  
  
Resize will change paper size and do fit-to-page with it.   
Then scale will scale ONLY the contents AFTER it.  
  
That would be something like:
```bash
# resize to A4 and scale to 90% (minus 10%)
pdfscale -r a4 -s 0.9 myFile.pdf
```
This would make the paper A4 and shrink the contents (creating a "border").    
  
There are many examples on this on the readme.md.  
Cheers!

**Comment by tavinus** [comment]
I am going to suppose the answer I provided was the solution, since there was no reply for 16 days.  
Feel free to reopen here if you want to.  
  
Cheers!
Gus
