### ISSUE TITLE
Resize without `-dPDFFitPage` to be able to add right margin

### ISSUE THREAD

**Issue by boillodmanuel** [tavinus/pdfScale#15]
Hello,

I had use you awesome script (congrats) to add a right margin to document.
I was able to do it by removing the `-dPDFFitPage` argument in resize command.

It could be great to add an option to do that in you script.

Best regards,

Manuel

**Comment by tavinus** [comment]
Merged on `v2.4.4`  
Thanks for the contribution!!

**Comment by tavinus** [comment]
**BTW**, another option would be to run in mixed mode with scale `1` (100% / no scaling).  
  
This way you could run the scaling mode without scaling anything.  
And then would be able to position the pages with the parameters:
 - `--hor-align, --horizontal-alignment <left|center|right>`
             Where to translate the scaled page
             Default: center
             Options: left, right, center
 - `--vert-align, --vertical-alignment <top|center|bottom>`
             Where to translate the scaled page
             Default: center
             Options: top, bottom, center
 - `--xoffset, --xtrans-offset <FloatNumber>`
             Add/Subtract from the X translation (move left-right)
             Default: 0.0 (zero)
             Options: Positive or negative floating point number
 - `--yoffset, --ytrans-offset <FloatNumber>`
             Add/Subtract from the Y translation (move top-bottom)
             Default: 0.0 (zero)
             Options: Positive or negative floating point number
  
I am gonna leave the option to disable the fit-to-page option anyways, just changed it to (yes/no), but still accepts f/fit.

**Comment by boillodmanuel** [comment]
👍
