### ISSUE TITLE
Architectural paper size names in command line arguments rejected as invalid.

### ISSUE THREAD

**Issue by teneighty-yvr** [tavinus/pdfScale#25]
The command line argument is made case insensitive by converting it to lowercase but the strings in the script contain uppercase characters in the names of architectural paper sizes so they can never match the argument. I changed the names stored in the script to lowercase and it has been working great. Easy fix. Thank you for the excellent script!

Version of pdfScale:
  Gustavo Arnosti Neves - 2016 / 07 / 10
  Latest Version - 2020 / 04 / 04

I haven't gotten to the point of making pull requests, so here's my diff output:

```
1631,1635c1631,1635
< archE 36.0 48.0 914 1219 2592 3456
< archD 24.0 36.0 610 914 1728 2592
< archC 18.0 24.0 457 610 1296 1728
< archB 12.0 18.0 305 457 864 1296
< archA 9.0 12.0 229 305 648 864"
---
> arche 36.0 48.0 914 1219 2592 3456
> archd 24.0 36.0 610 914 1728 2592
> archc 18.0 24.0 457 610 1296 1728
> archd 12.0 18.0 305 457 864 1296
> archa 9.0 12.0 229 305 648 864"
1741c1741
< 11x17 ledger legal letter lettersmall archE archD archC archB archA \
---
> 11x17 ledger legal letter lettersmall arche archd archc archb archa \
```

**Comment by tavinus** [comment]
Thanks for posting. 
Fixed!
