### ISSUE TITLE
Licence missing

### ISSUE THREAD

**Issue by beneklins** [tavinus/pdfScale#26]
First of all, thank you for pdfScale, it is really great!

However, I noticed that the repository does not have a licence file. There is a mention in the README file that the software is “free”, but could you specify under what terms the software is released?

[Michael J. Cole's code snippet](https://stackoverflow.com/a/27670586) is released under a [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) due to the way StackOverflow works. Thus, correct me if I am wrong, but this project should also be released under a CC BY-SA 4.0. Another alternative would be to release it under the GPLv3 licence, since the [CC BY-SA 4.0 is one-way compatible with the GPLv3](https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses/).

**Comment by tavinus** [comment]
Hi. So far this is not really using a proper license.  
  
The original Snippet is probably ZERO PERCENT of the code, so it is irrelevant. The original snippet just gave some inspiration, not really code.    
  
I am still undecided if I should use GPL or CC here.   
  
At this moment I can confirm it is free to use and you should use at your own risk. You can also use it into any GPL, CC, MIT, whatever thingy you may want. I care not. It just would be nice not to steal everything and tell everyone you did it yourself.  
  
I will probably upgrade the license when I have time to roll out the long waiting update I have here (will probably be v3). At that time I will also change the v2 license (or not LOL).  
  
I reserve the right to change the license if and whenever I see fit though.  
  
Cheers  
Gus
