### ISSUE TITLE
Unquoted $0 in basename $0 - basename: extra operand issues

### ISSUE THREAD

**Issue by brozkeff** [tavinus/pdfScale#40]
Variable PDFSCALE_NAME does not properly doublequotes "$0" variable for the subshell running basename command: "$(basename $0)" 

When script is run in a folders where some contain spaces or other characters errors such as "basename: extra operand ..." appear due to variable expansion.
The correct way is to doublequote also $0:
PDFSCALE_NAME="$(basename "$0")"

This PR fixes the issue and bumps the version up to 2.5.6: https://github.com/tavinus/pdfScale/pull/39

**Comment by tavinus** [comment]
I see.  
This variable is only used for printing information on screen, but it still should be fixed to avoid those errors.  
I will give a check on the PR now...

**Comment by tavinus** [comment]
Fixed on https://github.com/tavinus/pdfScale/pull/39
