### ISSUE TITLE
Ghostscript complains about the old PDF interpreter being deprecated

### ISSUE THREAD

**Issue by alexbuisse** [tavinus/pdfScale#44]
Hi,
Not a major issue as things seem to otherwise be working, but I am getting the following error message when running pdfscale to resize some Illustrator PDFs.

`PdfScale: ERROR!
Ghostscript Debug Info:
The old, written in PostScript, PDF interpreter has been removed entirely.
You should cease using -dNEWDPF as it has no effect now.
Continuing to process PDF file using the new, written in C, PDF interpreter.`

The command being run is 
`pdfscale -v -r 'custom pt 2574 1724' -c full "MBL - trollveggen - A0.pdf" "MBL - trollveggen - 60x90.pdf"`

And the verbose output:

`pdfscale v2.5.8 - Verbose Execution
  Single Task: Resize PDF Paper
        Dry-Run: FALSE
     Input File: MBL - trollveggen - A0.pdf
   Output File: MBL - trollveggen - 60x90.pdf
 Get Page Size: Adaptive Enabled
        Method: Grep
  Source Width: 3382 postscript-points
 Source Height: 2395 postscript-points
    Print Mode: Print ( auto/empty )
  Scale Factor: Disabled (resize only)
   Fit To Page: Enabled (default)
   Auto Rotate: PageByPage
   Flip Detect: No change needed
  Run Resizing: CUSTOM ( 2574 x 1724 ) pts
 Cropbox Reset: FULLSIZE ( 2574 x 1724 ) pts
  Final Status: Error detected. Exit status: 0`

pdfscale version is 2.5.8 and ghostscript is 10.02.1 (2023-11-01), running on macOS Sonoma 14.0 and Apple silicon.

**Comment by DXXS** [comment]
Got this here too, with gs 10.0

**Comment by cgbarnwell** [comment]
Everything seems to work, but the message is annoying.

I just deleted that line, and everything seems OK.  It would be interesting to know why anybody put it in there.

**Comment by tavinus** [comment]
Some versions of GS require it. I will change it to an optional parameter.

**Comment by tavinus** [comment]
v2.5.9 added the `--newpdf` parameter and disabled using `-dNEWPDF=false` by default.  
Cheers
